Table items {
  id ObjectId [pk, increment]
  item_description varchar
  category_id int 
  created_at timestamp
  created_by varchar
}

Table Locations {
  id int [pk, increment]
  location_name varchar [unique, not null]
  created_at timestamp
  created_by varchar
}

Table item_category {
  id int [pk, increment]
  category varchar 
  description varchar
  created_at timestamp
  created_by varchar
}

Ref: items.category_id > item_category.id